---
- name: Restart chrony service
  service:
    name: chrony
    state: restarted

- name: Restart postfix
  service:
    name: postfix
    state: restarted

- name: Restart sshd service
  service:
    name: sshd
    state: restarted

- name: Restart systemd-logind service
  service:
    name: systemd-logind
    state: restarted

- name: Restart zfs-zed
  service:
    name: zfs-zed
    state: restarted

- name: Enable weechat service
  service:
    name: weechat
    enabled: yes

- name: Re-export exportfs
  command: exportfs -arv
